Project NBbang {
    database_type: 'PostgreSQL'
    Note: 'NBbang 프로젝트 ERD'
}

Table public.USER {
    id serial [pk, unique, not null, note: '유저의 PK']
    oauth_type enum [not null, default:null, note: 'oAuth 로그인 타입']
    nickname varchar(20) [not null, note: '유저의 닉네임']
    name varchar(15) [not null, note: '유저의 이름']
    phone_num varchar(15) [not null, note: '유저의 연락처']
    type USER_TYPE [not null, default:'USER', note: '유저의 역할 (유저, 관리자, 어드민)']
}

enum USER_TYPE {
    "USER" [note: '일반 유저']
    "MODERATOR" [note: '관리자']
    "ADMIN" [note: '어드민']
}

Table public.ACCOUNT {
    id serial [pk, unique, not null, note: '계좌의 PK']
    user_id serial [not null, note: '계좌의 주인']
    account_num varchar(20) [not null, note: '계좌번호']
    bank_name varchar(30) [not null, note: '은행 이름']
    suspend boolean [not null, default:false, note: '정지 여부']
    suspend_id serial [note: '정지 ID']
    deleted boolean [not null, default:false, note: '삭제 여부']
    verfied boolean [not null, default:false, note: '실명 인증']
    created_date timestamp [not null, default:`now()`, note: '생성 시간']
    updated_date timestamp [not null, default:`now()`, note: '수정 시간']
}

Table public.TRANSACTION {
    id serial [pk, unique, not null, note: 'Transaction의 PK']
    sender_id serial [not null, note: '입금자의 ID']
    receiver_id serial [not null, note: '예금주의 ID']
    sender_account_id serial [not null, note: '입금자의 계좌 ID']
    receiver_account_id serial [not null, note: '예금주의 계좌 ID']
    status TRANSACTION_TYPE [not null, note: '현재 트랜잭션의 상태 (입금 대기중, 입금 완료)']
    created_date timestamp [not null, default:`now()`, note:'생성 시간']
    updated_date timestamp [not null, default:`now()`, note:'수정 시간'] 
}

enum TRANSACTION_TYPE {
    "TRANSFER_WATING" [note: '입금 대기 중']
    "TRANSFER_VERIFYING" [note: '입금 확인 중']
    "TRANSFER_CONFIRMED" [note: '입금 완료']
}

Table public.GROUP {
    id serial [pk, unique, not null, note: '그룹의 PK']
    name varchar(30) [unique, not null, note: '그룹 이름']
    member_count decimal [not null, note: '그룹의 가입자 수']
    member_admin serial [not null, note: '그룹의 관리자']
    created_date timestamp [not null, default:`now()`, note: '그룹 생성일']
    updated_date timestamp [not null, default:`now()`, note: '그룹 수정일']
    visibility boolean [not null, default:True, note: '공개 여부']
    registration_type REGISTRATION_TYPE [not null, default:'APPLY', note: '그룹의 가입 방법']
    suspend SUSPEND_TYPE [not null, default:'NONE', note: '그룹 정지 여부']
    deleted boolean [not null, default:false, note: '삭제 여부']
    suspend_id serial [note: '정지 ID']
}

enum REGISTRATION_TYPE {
    "SELF_ENROLLMENT" [note: '신청 가능']
    "INVITATION_ONLY" [note: '초대만 가능']
}

enum SUSPEND_TYPE {
    "NONE" [note: '없음']
    "TEMPORARY_SUSPEND" [note: '기간 정지']
    "PERMANT_SUSPEND" [note: '영구 정지']
}

enum GROUP_ENROLLMENT_ELIGIBLE_USER {
    "NEWCOMER" [note: '신규 가입자']
    "REJECTED" [note: '이전에 가입이 거부된 사용자']
    "LEAVED" [note: '그룹에서 탈퇴한 사용자']
    "BANNED" [note: '그룹에서 추방된 사용자']
}

Table public.USER_GROUP_MAP {
    id serial [pk, unique, not null, note: '유저, 그룹 매핑 테이블 PK']
    user_id serial [not null, note: '유저의 ID']
    group_id serial [not null, note: '그룹의 ID']
    created_date timestamp [not null, default:`now()`, note: '그룹 가입 일자']
    updated_date timestamp [not null, default:`now()`, note: '유저의 그룹 상태 최종 수정일자']
    deletd boolean [not null, default:false, note: '삭제 여부']
    status enum [not null, default:'WAITING_ACCEPTANCE', note: '현재 그룹의 가입 상태 (가입 중, 정지, 탈퇴, 강퇴)']
    rank enum [not null, default:'USER', note: '그룹에서의 랭크 (일반 유저, 운영진, 관리자)']
}

enum USER_GROUP_CURRENT_STATUS {
    "WAITING_ACCEPTANCE" [note: '가입 대기 중']
    "REJECT" [note: '가입 거절']
    "ACTIVE" [note: '활동 중']
    "SUSPEND" [note: '활동 정지']
    "LEAVE" [note: '탈퇴']
    "BAN" [note: '강퇴']
}

Table public.PENALTY {
    id serial [pk, unique, not null, note: '제재 PK']
    type PENALTY_TYPE [not null, note: '제재 종류']
    ref_id serial [not null, note: '제재 받는 주체의 ID']
    ref_type PENALTY_TARGET [not null, note: '제재 받는 주체']
    Note: '사용자 제재 테이블'
}

enum PENALTY_TYPE { 
    "SUSPEND" [note: '정지']
}

Table public.SUSPEND {
    id serial [pk, unique, not null, note: '정지 ID']
    penalty_id serial [unique, not null, note: '제재 ID']
    target SUSPEND_TARGET [not null, note: '정지를 참조하는 타입 (유저, 그룹)']
    ref_id serial [not null, note: '정지 참조의 ID']
    type PENALTY_TARGET [not null, default:'DURATION', note: '정지 타입']
    manager_id serial [not null, note: '정지 처분을 내린 운영진 ID']
    notes varchar [note: '정지 처분 노트']
    created_date timestamp [not null, default:`now()`, note: '정지 처분 생성 날짜']
    updated_date timestamp [not null, default:`now()`, note: '정지 처분 수정 날짜']
    duration timestamp [not null, note: '정지 기간']
    suspend_start timestamp [not null, default:`now()`, note: '정지 처분 시작 일자']
    suspend_end timestamp [not null, default:`now()+duration`, note: '정지 처분 종료 일자']
    Note: '정지 제재 테이블'
}

enum PENALTY_TARGET {
    "USER" [note: '유저']
    "GROUP" [note: '그룹']
}

Table public.GROUP_MEMBER_PENALTY {
    id serial [pk, unique, not null, note: '그룹 처벌 PK']
    member_id serial [not null, note: '정지된 멤버의 ID']
    type suspend_type [not null, default:'DURATION', note: '정지 타입']
    group_manager_id serial [not null, note: '정지 처분을 내린 그룹 운영진 ID']
    notes varchar [note: '정지 처분 노트']
    created_date timestamp [not null, default:`now()`, note: '정지 처분 생성 날짜']
    updated_date timestamp [not null, default:`now()`, note: '정지 처분 수정 날짜']
    duration timestamp [not null, note: '정지 기간']
    suspend_start timestamp [not null, default:`now()`, note: '정지 처분 시작 일자']
    suspend_end timestamp [not null, default:`now()+duration`, note: '정지 처분 종료 일자']
    Note: '그룹 운영자가 그룹원에게 제재를 가하는 테이블'
}

Ref: public.USER.id < public.ACCOUNT.user_id

Ref: public.USER.id < public.USER_GROUP_MAP.user_id

Ref: public.GROUP.id < public.USER_GROUP_MAP.group_id

Ref: public.USER.id <> public.SUSPEND.ref_id

Ref: public.GROUP.id <> public.SUSPEND.ref_id

Ref: public.USER.id <> public.GROUP_MEMBER_PENALTY.member_id

Ref: public.PENALTY.id <> public.SUSPEND.penalty_id